### ISSUE TITLE
NULL Count instead of actual count on some visusalization API Reports

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#1218]
Please help us help you by filling out the following sections as thoroughly as you can.

**Description:**
As an example: 
For this URL: 
http://augur.coronashelterfun.com:5044/api/unstable/contributor_reports/returning_contributors_stacked_bar/?repo_id=1

There are flyby contributors, but there is a NULL value in the count displayed. 

![image](https://user-images.githubusercontent.com/379847/113324902-46e87800-92dd-11eb-8eb4-9e71cf4571ff.png)

**Comment by yumberrjack** [comment]
The relevant code I have been looking over is the contributer_worker.py file.
I believe there is a logic error in the SQL query for the userSQL. The worker runs the SQL query at line 58 to find all the combinations of emails and names by searching through the queries commits. There are some areas of the code I don’t quite understand such as line 67: “WHERE repo_id = :repo_id” which has one colon while inside of the SELECT statement of the query it has: “cntrb_created_at::timestamp.” I am not sure if there is supposed to be continuity there or not, but that was one of the discrepancies I notice. It seems that this format is continued throughout the SQL query, so it seems it could be the correct way, I personally have just not seen colons used this way in SQL.
 
The reason I think that the issue is rooted in the SQL is that all the statements below look continuous and they just use the values grabbed from the SQL query, so it makes sense that the issue with the NULL values being used could be with that.
 
I think it is possible that the SQL query may be grabbing some NULL values, and there is not error check to make sure not to add data if the query is NULL. Maybe the query is grabbing some NULL values and there is some data connected to them, and they are added to the commit_cntrbs array. I personally think a solution to this issue is this:
Add a NULL value check at line 112 that checks to make sure whatever tuple value is being read is not NULL while the main tuple value is NOT NULL. This would look something like this:
 
if tuple[‘cntrb_id’] == NULL:
              continue
 
This would skip the values from that tuple being added to the contributor list.
I may be wrong, but that seems to be the only thing that I could see would produce NULL values in the contributors list and result in a contributor count reading in a NULL value. Seems too simple to be the fix but sometimes it’s the simplest things that cause these NULL value logical errors.

**Comment by ABrain7710** [comment]
Unable to replicate issue
