### ISSUE TITLE
VueJS app is not in production mode

### ISSUE THREAD

**Issue by KShivendu** [chaoss/augur#1249]
**Description:**
I was going through the output in the browser console and I discovered that multiple requests were sent to different endpoints of `http://augur.osshealth.io:5055/api/` and they were called from `.ts` files. I might be wrong but I don't expect .ts files to be found in production mode. I think this might be a bug. 

**How to reproduce:**
1. Go to `http://augur.osshealth.io/errors`
2. Use F12 to open Chrome Dev Tools
3. Read the logs

**Expected behavior:**
If the Vuejs web app is in production mode then all the .ts files should get compiled to .js files

**Log files**
```
http://augur.osshealth.io:5055
AugurAPI.ts:104 http://augur.osshealth.io:5055/api/unstable/repos
AugurAPI.ts:104 http://augur.osshealth.io:5055/api/unstable/repo-groups
AugurAPI.ts:104 http://augur.osshealth.io:5055/api/unstable/top-insights
AugurAPI.ts:104 http://augur.osshealth.io:5055/api/unstable/metrics/status/filter
AugurAPI.ts:104 http://augur.osshealth.io:5055/api/unstable/metrics/status/metadata
AugurAPI.ts:34 http://augur.osshealth.io:5055
AugurAPI.ts:104 http://augur.osshealth.io:5055/api/unstable/repos
AugurAPI.ts:104 http://augur.osshealth.io:5055/api/unstable/repo-groups
AugurAPI.ts:104 http://augur.osshealth.io:5055/api/unstable/top-insights
AugurAPI.ts:104 http://augur.osshealth.io:5055/api/unstable/metrics/status/filter
AugurAPI.ts:104 http://augur.osshealth.io:5055/api/unstable/metrics/status/metadata
AugurAPI.ts:34 http://augur.osshealth.io:5055
AugurAPI.ts:104 http://augur.osshealth.io:5055/api/unstable/repos
AugurAPI.ts:104 http://augur.osshealth.io:5055/api/unstable/repo-groups
AugurAPI.ts:104 http://augur.osshealth.io:5055/api/unstable/top-insights
AugurAPI.ts:104 http://augur.osshealth.io:5055/api/unstable/metrics/status/filter
AugurAPI.ts:104 http://augur.osshealth.io:5055/api/unstable/metrics/status/metadata
actions.ts:42 setting base repo w payload:  Object
actions.ts:264 about to add repo:  undefined undefined undefined undefined undefined
actions.ts:276 
```
**Software versions:**
 - OS: Ubuntu
 - Browser: Chrome

**Comment by sbrennan98** [comment]
Hello Kumar. Thank you for the heads up!

I went ahead and looked into this issue and, after about ten hours of looking into it and the documentation for Vue CLI & Webpack, I can say with ~98% certainty that it's actually a nonissue.

While all typescript is ultimately transcompiled into javascript, it is my understanding that the logs from the ```.ts``` files in the dev console are okay and not indicative of whether the application is in production mode or otherwise. Both modes have source mapping by default and I believe that is how the dev console is able to tell which files the print commands are coming from. To verify the frontend was indeed in production mode, I tested the frontend application as it stands and then ran a test against a build that was explicitly built in developer mode with the custom npm script ```NODE_ENV=development vue-cli-service build --mode=development``` I added to the Webpack ```package.json```. Comparing both developer consoles, the latter prompted me to install the Vue Devtools browser extension while the former did not which would imply it is indeed in production mode.

Regardless, thank you very much for bringing this to our attention!
