### ISSUE TITLE
Augur Zapier Notification System

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#1323]
Explore the use of Zapier as a tool for sending diverse notifications in diverse formats (email, slack, text, etc.)  Important for push notification, and open to a developer's imagination!

https://zapier.com/

**Comment by 47carolines** [comment]
@JMerkel3100, @bargainbin and I created an Augur Zapier Integration that can be modified to work for your own Augur server. We used this integration in order to create a Zap which ultimately allows you to receive push notifications in Slack whenever a Augur REST API endpoint is updated. Learn how to create a Zap similar to ours and find the invitation link to our integration here: https://github.com/47carolines/CS4320GroupProject

**Comment by sgoggins** [comment]
We've found a free service.
