### ISSUE TITLE
Create Schema should be idempotent and survive errors

### ISSUE THREAD

**Issue by jberkus** [chaoss/augur#1355]
## The way it is now

Database initialization happens via a manual command.  If a schema already exists (or any DB error is encountered), the augur backend fails and does not start workers.  Part of this is because the schema is loaded via psql instead of using SQLAlchemy models.

This becomes particularly pathological when running Augur in a container, as the `AUGUR_DB_SCHEMA_BUILD=0` is stateful, and needs to be passed at container creation.  So this results in the user needing to manually create a separate "init" container that creates the schema and run it manually before deploying the actual runtime container.  This will not work at all in a Kubernetes environment.

Further, the current psql load script is not capable of distinguishing between types of load errors, so any error at all is fatal.

## The path forwards

The best way to solve this is to replace the entire contents of /schema/ with a set of SQLAlchemy models and use Alembic.  Unlike loading files via psql, SQLAlchemy operates via a "desired state" approach, in which it checks the currently loaded database, if any, and then brings it into compliance with the models.  Not only would this make schema creation idempotent, it would also enable us to manage schema upgrades.

Discuss?

**Comment by sgoggins** [comment]
I see the clear software engineering advantages of this approach. To date I've rigorously managed the schema (it's one part of Augur I stick my nose into on every update, enabling some greater confidence that errant code cannot (easily) corrupt data.).

Because we enforce foreign keys and value constraints in (most, with the aim of all) cases, I have above average confidence that critical data rules cannot be violated with a software update. Errors show up reliably in testing and get fixed. 

A couple questions:
1. I think this is a useful value system. This choice arises from my own frustration with how data isn't verified as complete or correct in other tools for making software health and sustainability visible. 
2. Do you recommend any tools for reverse engineering model files from an existing schema and tracking schema evolution?

**Comment by sgoggins** [comment]
I.e. : we don't get this from jamming json into elastic search.

**Comment by jberkus** [comment]
> Do you recommend any tools for reverse engineering model files from an existing schema and tracking schema evolution?

https://pypi.org/project/sqlacodegen/ seems to be the current main tool.  There's nothing that won't require us to hand-tweak the results, though, so it's not like we can auto-generate this from a schema maintained elsewhere and never touch the models by hand. So if we go ahead with this, that means that the model files will become the source of truth for the schema.

**Comment by jberkus** [comment]
Oh, and FYI: it is 100% possible for us to use SQLAlchemy models that include rigorous FK and other constraints.  It doesn't limit us that way.  The only things that are unsupported are a few Postgres-only features like partial indexes and how it does triggers.
