### ISSUE TITLE
Wrong Image Downloaded

### ISSUE THREAD

**Issue by howderek** [chaoss/augur#211]
**Describe the bug**
When I download images of the charts, the first chart is always downloaded. The filename appears correct, but the image is not.

**To Reproduce**
Download any image from any chart except the first

**Expected behavior**
The chart above the download button is downloaded

**Comment by ccarterlandis** [comment]
Fixed in `dev` as of [this](https://github.com/chaoss/augur/commit/9478092def4650f70a85e4a65d832acef4d5b3ba) commit. The issue was that there was reference to something that used to be named `chartholder` and is now named `holder` instead. This was erroring out and instead of presenting a message, was just downloading the first chart by default (for some reason).
