### ISSUE TITLE
Baseline and Raw Score: They are Different Things

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#212]
**Describe the bug**
The "baseline" option now shows the "raw score".  We should update what the text says or configure a "baseline" comparison. I think we did decide to shift the visualizations to raw score comparisons, so I think the fix is simply updating the text as shown below. 

**To Reproduce**

<img width="736" alt="screenshot 2018-12-29 13 53 21" src="https://user-images.githubusercontent.com/379847/50541737-56623f00-0b71-11e9-86b7-f8f574097e75.png">

**Expected behavior**
Raw score: The raw data mapped on the visualization. 
Baseline comparison: The base repo is a zeroed out line acorss the x-axis, and the compared projects are shown in comparison to the "baseline" of the base project. 

**Screenshots**
above. 

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by gabe-heim** [comment]
How this was actually configured (which was still incorrect given that I was unsure of what 'baseline' was) was that baseline was showing the rolling average, zscore was showing the zscore, and nothing was showing what baseline is supposed to be. It turns out that I had broken the raw values option at some point, but I just fixed it. I will look into getting 'baseline' to work as expected. I am wondering if we should have 3 radio buttons there? With the 3rd being "Rolling Average"? This seems like a necessary option to me.

**Comment by gabe-heim** [comment]
Another thing to think about is, with whatever the comparison option is, if the user also has raw values shown, should we have the raw values put under the effect of the comparison option? Attached is an example where z-score and raw values are selected, should we compute the zscore of the raw data points and display those? Or the actual raw data?
<img width="603" alt="screen shot 2018-12-30 at 12 08 56 pm" src="https://user-images.githubusercontent.com/20764846/50549941-0f854f80-0c2c-11e9-8fa7-90bd61cf63a7.png">

**Comment by gabe-heim** [comment]
A 3rd option, 'Rolling Average', is now available which is self explanatory. The baseline option now works as expected as well.
