### ISSUE TITLE
License Information Metric

### ISSUE THREAD

**Issue by abuhman** [chaoss/augur#25]
Update on search for ways to get license information:

I looked into DoSOCSv2 for license information.  It examines project files that are present locally.  We would have to download a project's files from GitHub in order to run something similar.  I think it might be technically possible to download the files automatically.  We could use the API's contents to get the download URL https://developer.github.com/v3/repos/contents/#get-contents and then download using that URL.  However, I'm not sure downloading and storing entire projects, even temporarily, would be viable in terms of speed and storage.

As far as I can tell, DoSOCSv2 uses https://github.com/ardumont/fossology-nomossa to examine files for license information.  Fossology lists the following as things it uses.  The top two would appear to scan files for license information (though I haven't looked in depth into either Nomos or Monk).

    Nomos, a license scanner based in regular expressions.
    Monk, a license scanner based on text comparison.
    MonkBulk, an extension to Monk for user-based phase searching.
    Copyright, an Agent searching for copyright, URL, e-mail and authorship statements.
    ECC, export control and customs as an extension to Copyright.
    Package Agent, an agent exporting metadata from installation packages.
    Maintenance Agent, (new in 2.4.0)
    Mimetype Agent, running over files trying to determine the mimetype.
    Buckets, an agent to categorize files based un user-defineable definitions.

**Comment by germonprez** [comment]
Yes, it essentially strips away FOSSology to simply get at Nomos, the scanner

Regarding the download, yea, it would really have to come from the repository. I wouldn't expect to store the package locally but you are right -- downloading and scanning is a time-consuming process. Yet, this is pretty important information and we could leave it to a user to decide if they want to pay that overhead for that information.

**Comment by ChristianCme** [comment]
It seems like the GitHub API already aggregates license information https://developer.github.com/v3/licenses/

**Comment by germonprez** [comment]
It may but not to level of identifiability of something like Nomos, or LiD (Qualcomm's new scanner). I believe that in the case of GH, the license would have to be declared by the repo owner. In the case of the scanners, they can look for identifiable text that the repo owners may not have declared.

**Comment by abuhman** [comment]
https://help.github.com/articles/licensing-a-repository/

I think the API is getting it from the files license.txt or license.md.

"The open source Ruby gem Licensee compares the repository's LICENSE file to a short list of known licenses. Licensee also provides the Licenses API and gives us insight into how repositories on GitHub are licensed. If your repository is using a license that isn't listed on the Choose a License website, you can request including the license.

If your repository is using a license that is listed on the Choose a License website and it's not displaying clearly at the top of the repository page, it may contain multiple licenses or other complexity. To have your license detected, simplify your LICENSE file and note the complexity somewhere else, such as your repository's README file."

**Comment by howderek** [comment]
Since using the API is trivial compared to using third party software, I suggest we start by using the API and if we find it doesn't meet our needs we can put more effort into getting better license data further down the line.

The challenge with many more robust license scanners is that they require downloading the project. Unless we drastically limit our search space, we don't have the storage nor compute resources to provide that kind of data. Even if we did have those resources, how long could we sustain that for?

The advantage of using the API is we can trust that it will be around as long as GitHub is. The link that @abuhman posted referred to the [Licensee](https://github.com/benbalter/licensee) project, which detects all of the licenses on https://choosealicense.com/ 

The License API is more sustainable than these other projects :)

**Comment by GeorgLink** [comment]
The License information is part of the [Risk Health](https://github.com/OSSHealth/HealthIndicators/blob/master/CCCIndicators.md#compliance-risk-health):

**License Declared** can be answered by the API.

**License Coverage**, **License Conflict**, and **License Count** can only be answered by scanning all files in the repository.

Comment: The scanning is not trivial. Binaries or images might not have declared licenses and might or might not be counted in the overall percentage.

**Comment by abuhman** [comment]
What I've been finding online was that if a license isn't declared for something, you should assume that you can't use it.  Maybe we should output something along those lines to the user in the event we don't find a license?

**Comment by germonprez** [comment]
An argument for more detailed license information is their critical importance in OSS -- not just at the project level but also at the file level. I think that GH only provides license information at the package level (could be wrong). Things like reported % of files with declared license can be very interesting. So too with the different licenses throughout a single package. As @GeorgLink points out, risk health is pretty important for many/all of these organizations. 

It is true that it would entail a download and that is a big overhead. No doubt there. I don't think that we would hold the actual downloaded package post scan. Nor would we necessarily have to hold the results. 

I'm suspecting that the tools I mentioned above will be around for a while based on their Linux Foundation and corporate support. You never know though. 

@abuhman - yes, no license you can't assume use. Source available but not open source.

**Comment by sgoggins** [comment]
@abuhman and @germonprez : What are your thoughts on putting some of the license work into the ghdata project road map?

**Comment by sgoggins** [comment]
I think the scope of what's in Cold Fusion is the License Declared info that Georg mentioned above/ yes?

**Comment by GeorgLink** [comment]
I lost the context: What is Cold Fusion?

**Comment by sgoggins** [comment]
@GeorgLink : I think we are unsure how to measure this right now.  Is there a metric defined?

**Comment by GeorgLink** [comment]
We currently have the section ["Copyright and License Factors"](https://github.com/chaoss/metrics/blob/master/3_Risk.md#copyright-and-license-factors) that speaks to license metrics. Right now, the qualitative license metric that is a list of licenses in a project.

At one point, we were discussing a quantitative metric, but dropped the idea for now.

**Comment by sgoggins** [comment]
@GeorgLink : Since there is an option to specify a license on a GitHub repository, do you think we should provide this information where available, or some aggregate navigation between projects with similar licensing policies at a "gestalt" instead of at the repository level? 

@howderek , here is the text from below and I think some of these "Activity Metrics" be put on our implementation path: 


Activity Metric | Description
-- | --
Copyright Declaration | The degree to which the project properly declares copyright ownership, including the copyright symbol or 'copyright' word, the year of the creation, the name of the author, and a rights statement.
Package License Declaration | A list of license declarations on the software package.
File License Declarations | A list of license declarations on the software package files.
License Identification Methods | A list of methods or tools used for identifying licenses in files.

**Comment by GeorgLink** [comment]
If you would only show the repository level license that is obvious from looking at the GitHub repository, then there is no additional information GHData would be providing and thus I do not see it as valuable. 

Can you elaborate on the "gestalt" idea?

**Comment by howderek** [comment]
Closed due to inactivity
