### ISSUE TITLE
Missing dates on time-axis

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/augur#259]
**Describe the bug:**
In the screenshot, the top graph does not have dates on the x-axis. It might easily appear that the dates from the bottom graph apply also to the top graph, but this cannot be true, especially when selecting time boundaries in the bottom graph to filter what shows in the top graph.

**To Reproduce:**
1. Go to http://chaoss.augurlabs.io/singlegit/gmd/github.com%2Fchaoss%2Fwebsite.git
2. See error

**Expected behavior:**
Possible solution: Add dates to top graph. 

**Screenshots**
![image](https://user-images.githubusercontent.com/8862021/55257264-5257c300-522d-11e9-896b-05b7e04c563a.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Firefox 66.0.1

**Additional context**
N/A

**Comment by bing0n3** [comment]
I tried to fix the issue. By my understanding, it seems like it can be fixed by changing the attribute "labels" in [DynamicLineChart.vue](https://github.com/chaoss/augur/blob/hotfix/frontend/app/components/charts/DynamicLineChart.vue) line 172 from `!this.showDetail`  to `this.showDetail`. 

Original: 
https://github.com/chaoss/augur/blob/5def6b4799febf91279d807a56fb281fb81fc7af/frontend/app/components/charts/DynamicLineChart.vue#L167-L173

[Fix](https://github.com/bing0n3/augur/commit/bbb9f7082398343b8c535ded41b6125f06f977a3#diff-e5d0efa0257f40e72c389fe71471bcc8):
```
"axis": {	                       
    "labels": this.showDetail,
    "format": "%b %Y",
    "title": " "
}
```

Screenshot:

<img width="568" alt="image" src="https://user-images.githubusercontent.com/15957393/55675457-ce3ab680-5890-11e9-87d6-c9e945cb4e62.png">


 If it make sense, I will try to create a pull request.

**Comment by GeorgLink** [comment]
The screenshot looks promising :+1

**Comment by gabe-heim** [comment]
@bing0n3 +1 from me too. Good catch! Feel free to create a PR.

**Comment by bing0n3** [comment]
I will create a PR soon.
