### ISSUE TITLE
Error running "augur" command in vagrant

### ISSUE THREAD

**Issue by parthsharma2** [chaoss/augur#266]
**Describe the bug:**
Running `augur` command in vagrant box results in a "SyntaxError: invalid syntax"

I think this happens because the command `augur` is trying to use python 3.5 to run the augur server instead of python 3.7

The vagrant box contains 3 different python versions:
`python`     -> python 2.7
`python3`   -> python 3.5
`python3.7` -> python 3.7

Changing the shebang of `augur` to `#!/usr/bin/python3.7` results in the following error:
`pkg_resources.ContextualVersionConflict: (requests 2.9.1 (/usr/lib/python3/dist-packages), Requirement.parse('requests>=2.14.0'), {'PyGithub'})`

Which I think is most probably due to `pip3` being linked to python 3.5

**To Reproduce:**
1. Start up the augur vagrant box
2. Try using the command `augur`

**Expected behavior:**
Running the command `augur` should start the augur server

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chrome 73.0.3683.75

**Comment by ccarterlandis** [comment]
I know why that issue occurs, but currently I don't know of a fix. During the provisioning process, the `vagrant` process (for whatever reason) doesn't recognize the use of `pip install` flags. It's super weird and I have zero idea why it happens, but it's the reason that after you spin up the vagrant box, you have to do `$AUGUR_PIP install --upgrade .` yourself (as documented in the [README.md](https://github.com/chaoss/augur#tldr)). Doing this will resolve the `pkg_resources.ContextualVersionConflict` error. While this isn't an ideal fix, we currently don't have the bandwidth to try and diagnose what seems to be a problem on Vagrant's end.

As far as for the 3 versions of Python are concerned, both Python 2 and 3.5 come already installed on the Ubuntu version. However, we do our development on version 3.7, so that's what get's used in all the `make` commands, as well as in `$AUGUR_PIP` and $AUGUR_PYTHON` for doing other Python things at the command line.
