### ISSUE TITLE
Creating a new metric endpoint visualization for lines_changed_by_week

### ISSUE THREAD

**Issue by Etoebben** [chaoss/augur#267]
**Describe the bug:**
Trying to add a line chart or other visualization for he lines_changed_by_week, we are unable to get the chart to show up. 

**To Reproduce:**
Steps to reproduce the behavior: our repo: https://github.com/computationalmystic/augur-group26, at this commit: https://github.com/computationalmystic/augur-group26/commit/7c9cecd02d8c01a6370c6a681e3fee35e61082be 

in the dev branch. 

1. Add this line to augurAPI.js: 
>       Timeseries(repo, 'linesChangedByWeek', 'lines-changed-by-week')
2. Add this section to a VUE card. We created LinesCard.vue, using a copy of git.vue ... Here's the lines we added:
```
    <div class="row">
        <div class="col col-12">
        <dynamic-line-chart source="lines_changed_by_week"
              title="new"
              :data="values['lines_changed_by_week']"
        </dynamic-line-chart>
        </div>
    </div>
```

These files were also modified : 
1. modified:   frontend/app/AugurAPI.js
2. modified:   frontend/app/components/Tabs.vue
3. modified:   frontend/app/router/router.js
4. modified:   frontend/package-lock.json
5. modified:   frontend/public/app.js

4. The image simply does not show up.

**Comment by gabe-heim** [comment]
Since the lines_changed_by_week function is for the facade datasource, you will actually have to use the GitEndpoint() function rather than Timeseries(). The dynamic line chart's source should be 'linesChangedByWeek' in your example (the second parameter). And make sure the 3rd parameter in the Timeseries()/GitEndpoint() functions match exactly the name of the python function (ie if the function name in datasources/facade/facade.py is 'lines_changed_by_week', then the function you call in AugurApi.js should be 'GitEndpoint(repo, 'linesChangedByWeek', 'lines_changed_by_week')'. Feel free to reopen if this does not solve your issue.
