### ISSUE TITLE
Augur front end "add" buttons on the "Repo Tracker" tab redirects to the change password page 

### ISSUE THREAD

**Issue by cdolfi** [chaoss/augur#2753]
When you click either add buttons it sends you directly to the change password page

**Comment by Ulincsys** [comment]
This occurs because the default section on the profile page is the `Profile` tab. When you click the Add button, your browser performs a request to the endpoint to create your new repo group or add your repos for tracking, and you are redirected back to the profile page. The action is successfully performed, but you are not brought back to the same section as where the action was performed from. You can check that the action was successful by navigating back to the Repo Tracker tab.

I'll look into fixing this when I'm back from break. I think it will require updating our redirection logic, but it is definitely possible.

**Comment by cdolfi** [comment]
@Ulincsys Sounds good, thanks!

**Comment by Ulincsys** [comment]
Fixed by #2783 
Currently in dev, but the changes are set to be in the next release
