### ISSUE TITLE
Database container port inconsistency

### ISSUE THREAD

**Issue by mhauru** [chaoss/augur#2772]
The main Makefile and a couple of pages in the documentation assume that the database Docker container is run so that the PostgreSQL port is 5434:
https://github.com/search?q=repo%3Achaoss%2Faugur%205434&type=code

However, some other places use the default port 5432. Here are a few files doing that, I'm not sure I found all of the cases:
https://github.com/chaoss/augur/blob/a786ac5a506ffac31931f40c2a58056b7c1f073c/scripts/control/refresh-matviews.sh
https://github.com/chaoss/augur/blob/a786ac5a506ffac31931f40c2a58056b7c1f073c/docs/new-install.md
https://github.com/chaoss/augur/blob/a786ac5a506ffac31931f40c2a58056b7c1f073c/docker-compose.yml#L13
https://github.com/chaoss/augur/blob/a786ac5a506ffac31931f40c2a58056b7c1f073c/augur/application/cli/db.py#L323

**Comment by GaryPWhite** [comment]
I _think_ this is an artifact of times gone by -- `augur_database` is not the same as the `postgres` container recently included in the compose file.

some of the [blame](https://github.com/chaoss/augur/blame/331b8e2b332117428deb3aa591d925bb6a58b239/Makefile#L93) shows this was done literally 4 years ago -- maybe the project has pivoted since then

**Comment by sgoggins** [comment]
@ABrain7710 : Can you look into this?
