### ISSUE TITLE
Two different types of style files

### ISSUE THREAD

**Issue by Etoebben** [chaoss/augur#282]
Describe the bug:
It seems like augur may be running two completely different style pages for the same pages.
The augur program seems to be utilizing the kube framework. In doing so it looks like kube set up a css file that issues style commands for what looks like all of the elements and classes.

The augur program also seems to be using Node Js styl files to load css. It too looks like it is assigning all of the elements and classes style commands.

While this can be worked around in most instances, it is very confusing for the developers. There have been instances when the style sheets conflict and cause the page to crash.

To Reproduce:
augur-group26/frontend/app/styles/augur.styl
augur-group26/frontend/app/styles/ghdata.styl
augur-group26/frontend/app/include/kube/kube.css

Expected behavior:
Augur file really need to limit its css per page to one.

**Comment by howderek** [comment]
Hello @Etoebben, thanks for your report! 

While there should not be duplicates of `augur-group26/frontend/app/styles/augur.styl` and `augur-group26/frontend/app/styles/ghdata.styl`, our web compiler framework Brunch takes care of compiling all of our stylesheets into one file at the very end. These duplicate files do not cause issues on the front-end, but we can see how it might be unclear which file to edit. We will remove ghdata.styl once we've got it all migrated into augur.styl.

I'm not sure what you mean by "the style sheets conflict and cause the page to crash." Even if the duplicate styles were loaded by the user, browsers just override previous styles with new ones. Can you give us an example of a 'conflicting' style that causes the page to crash so that we can see the behavior?

Also, we recommend developing off of the master branch. The `dev` branch is very fast-paced and often introduces breaking changes.
