### ISSUE TITLE
 twitter\twurl.git - Graphs not responding & header overlap

### ISSUE THREAD

**Issue by SanchitVerma** [chaoss/augur#362]
Description of the bug: 

Issue 1. For the Twitter\twurl.git repository the graphs are not responding on trying to switch between formats of style or timelines

Issue 2. For the Twitter\twurl.git repository there is an overlap of the main header and first graph's title

1. Go to 'http://dev.augurlabs.io/' 
2. Click on 'github.com/twitter/twurl.git' under Twitter
3. Scroll down to 'Lines of code added by the top 10 authors visualized' graph
4. Try to switch between 'Circle', 'Tick' and 'Rectangle' 
5. See error - graph's view does not change
6. Note similar behavior for other graphs on this page too

**Expected behavior:**
Graph's view should be updated based on the graph style/timeline selected  

**Screenshots**
Attached -
![Screen Shot 2019-08-28 at 12 05 02 PM](https://user-images.githubusercontent.com/46542791/63877827-f89b2680-c98d-11e9-9564-f43eb0647106.png)

**Desktop (please complete the following information):**
 - OS: macOS v10.14.6
 - Browser: Chrome Version 76.0.3809.100 (Official Build) (64-bit)

Note: Cross checked the issue on multiple desktops on full resolution

**Comment by gabe-heim** [comment]
Hi @SanchitVerma ! Thanks for opening this issue, we are actually in the process of redesigning a new frontend that will solve issues like these, have a whole lot more visualizations to explore, and have a brand new design that has a much cleaner look. We are currently getting it stable enough to push up to all of these instances. You can see a beta version of this frontend at http://augur.osshealth.io , as soon as we get the Twitter version up and running I will be sure to update you on this thread!

**Comment by Nebrethar** [comment]
This issue is still relevant, but it is with new graphs.

The graph "Lines of code added by the top 10 authors as Percentages - By Time Period" on the overview page does not respond.
The graph "Average Lines of Code Per Commit" responds visually, but changing graph options does not change anything. Examples below.

![image](https://user-images.githubusercontent.com/34951354/67951301-3cdabb00-fbb9-11e9-90fb-29381f1001e5.png)
![image](https://user-images.githubusercontent.com/34951354/67951324-45cb8c80-fbb9-11e9-8bbd-76cb6e5fdb1b.png)
![image](https://user-images.githubusercontent.com/34951354/67951377-5f6cd400-fbb9-11e9-8d00-3d36609745fe.png)

@gabe-heim @SanchitVerma

**Comment by Nebrethar** [comment]
The second problem seems fixed as the options at the bottom are removed. Closing issue
![image](https://user-images.githubusercontent.com/34951354/73282938-f4cb3480-41b7-11ea-983f-ededf98cb99d.png)
