### ISSUE TITLE
Some Unclear / Redundant Installation Questions

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#364]
**Describe the bug:**
Ambiguity and repetition can be avoided: 

If you need to install Postgres, the downloads can be found here: https://www.postgresql.org/download/
1) Would you like to use a pre-existing Postgres 10 or 11 installation to which you can install the Augur schema?
2) Would you like to use a pre-existing Postgres 10 or 11 installation to which someone else can install the Augur schema?
3) Would you like to use a pre-existing Postgres 10 or 11 installation with the Augur schema already installed? 
4) Skip this section
Your choice: 3
Please enter the credentials for your database.
Database: augur
Name: augur
Host: xxxxxx
Port: 5433
User: augur
Password: xxxxxx
Schema: augur_data
Key: xxxxxxxxxx
Zombie ID: 22
rm: temp.config.json: No such file or directory
Generating configuration file...
Beginning 'augur.config.json' creation process...

==Setting up Cache configuration==
==Setting up Augur Database==
Please enter your GitHub API key: Your choice: 3
Please enter the credentials for your database.
Database: augur
Name: augur
Host: nekocase.augurlabs.io
Port: 5433
User: augur
Password: xxxxx
Schema: augur_data
Key: xxxxxxxxxxx
Zombie ID: 22

**To Reproduce:**
Run the Augur Installer: `augurinstall.sh`

**Expected behavior:**
1. Database Name and Name are the same value, which is a defect in the config file we can fix later. Meanwhile, they are always the same. 
2. The schema should always be `augur_data` ... so we do not need to prompt for that.
3. "Key" is ambiguous, and we later prompt for the "GitHub API Key", which is the same value.  Another legacy defect we should refactor in the `augur.config.json` ... for now, prompt once for the `Github API Key`. 
4. Overall, installing it this morning with our three newest team members gives me an even stronger preference for serving up a web page for the installation. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS v10.14.1]

**Additional context**

**Comment by ccarterlandis** [comment]
Below are my fixes in [this](https://github.com/chaoss/augur/commit/1df2b605f6f663d6c972c33019614b63303df8f2) commit for the above issues:
1. Deleted the prompt for the `name` parameter from the script
2. Defaulted the `schema` parameter to `augur_data`
3. For now I've deleted the prompt for the `key` parameter from the script; I think we did use this for something in the past however, so I'm not sure if this was the right call - @gabe-heim can you confirm?
4. I agree that the GUI installation is the easiest use case for newcomers. I think we should harden this installation process as much as possible first, make sure it's well documented and tested, and then build the GUI part on top of it so that we don't have to worry about the instability of the underlying script.
