### ISSUE TITLE
Comparison's not working on `dev1

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#380]
**Describe the bug:**
Repo comparison functionality is broken in the dev branch. It does not show repo-groups or repos in the list. 

**To Reproduce:**
1. Download and run the latest version of Augur's `dev` branch. 

**Expected behavior:**
Comparisons to work. 

**Screenshots**

![Vue_App](https://user-images.githubusercontent.com/379847/64350268-05d39900-cfbe-11e9-89a0-2ef5a1e58cec.png)

**Desktop (please complete the following information):**
 - OS: [e.g. macOS v10.14.1]
 - Browser: [e.g. Chrome v64.5.13 or Safari v12.0.1]

**Comment by bing0n3** [comment]
I will work on it.

**Comment by Manojkakde** [comment]
Definitely I will work on this.

**Comment by bing0n3** [comment]
https://github.com/chaoss/augur/blob/94bdf850b07ef06074a54007b0dfb835ed87cf9e/frontend/src/store/modules/common/actions.ts#L191-L207

@sgoggins : The reason  Comparison broke is @gabe-heim comment out this code, so that we cannot commit repo_group data to cache.  Uncomment it  can fix the bug. Do you want me to fix it now because I didn't know why gabe comment out it?

**Comment by bing0n3** [comment]
@sgoggins: @gabe-heim has fixed it.
