### ISSUE TITLE
osshealth (augur) Risk pages not loading.

### ISSUE THREAD

**Issue by Nebrethar** [chaoss/augur#393]
**Describe the bug:**

**To Reproduce:**
1. Go to, for example, http://augur.osshealth.io/repo/CHAOSS%20Risk%20Working%20Group/openssl/risk

**Expected behavior:**
I expected the risk page to load

**Screenshots**
![image](https://user-images.githubusercontent.com/34951354/65452326-a58a8700-de06-11e9-9f3b-30d56028baeb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 76

**Comment by Nebrethar** [comment]
Just tried this on localhost: I'm not sure why but it loads all repo groups and repos when i go to the risk page. 
It also does not look like it is attempting to load risk data at all.

**Comment by gabe-heim** [comment]
@Nebrethar fixed in 37731cf1cd5af61445064d10c8108c30f5413bf3 . It loads the repo groups and repos occasionally if the page it is on needs a repo id (usually for re-setting the baseRepo in the vuex state, this logic can be found in frontend/src/Augur.ts) and that data is not already cached. Jsyk the fix for this included changing some of your old implementation by moving some of the risk endpoint calls to inside of the chart files, if anything looks confusing, dont hesitate to reach out!
