### ISSUE TITLE
Help wanted: install failed

### ISSUE THREAD

**Issue by dota17** [chaoss/augur#447]
Hi augur team!
When I try to install this lib according to the [document](https://oss-augur.readthedocs.io/en/master/getting-started/installation.html), I got a fail at step 2:
![augur_issue](https://user-images.githubusercontent.com/50514813/67650597-87212980-f978-11e9-8103-2d3517330f0d.png)
Is there anyone who can help me?
Thanks in advance!

**Comment by dota17** [comment]
@michaelwoodruffdev

**Comment by ccarterlandis** [comment]
Hi @dota17! What operating system are you running? Additionally, what are the file permissions for `util/scripts/install/install.sh`? Can you run that file by itself with using `make install`?

**Comment by dota17** [comment]
Sorry, I forgot to give some detail information about my PC.

`os`: Ubuntu 18.04.2 LTS (Bionic Beaver)
`make`: GNU Make 4.1 Built for x86_64-pc-linux-gnu

well, at first, it tells me that:
![augur_issue2](https://user-images.githubusercontent.com/50514813/67656075-b2fada00-f98d-11e9-8a1a-b2cedec221e4.png)
so, I changed its permission to `777`, then it tells me: 
```
make: ./util/scripts/install/install.sh: Command not found
Makefile:51: recipe for target 'install' failed
make: *** [install] Error 127

```
and when I run install.sh manually, it tells me:
```
bash: ./install.sh: /bin/bash^M: bad interpreter: No such file or directory
```
That's all. 
Thank you @ccarterlandis

**Comment by ccarterlandis** [comment]
Thanks for providing that information @dota17. Good news is that we officially support Ubuntu 18.04 and that the file permissions should be fine.

The "bad interpreter" error makes me think that the `^M` after the shebang is the problem. However, I don't see that on my version of `master`. What does the first line of `util/scripts/install/install.sh` look like? If it has that `^M`, delete it so that it reads `#!/bin/bash` and then run it again and see if that changes the output.

**Comment by dota17** [comment]
Thank you very much!
 The `^M` comes from the windows, casue I use Git for Windows Desktop to clone this lib.

PS: I have tried to download .zip package directly instead of cloning it, but there are some problems to unzip it.
```
 Unexpected end of archive
```

**Comment by ccarterlandis** [comment]
Ah, that would explain things. We do not officially support local Windows installation at this time, so I'm not surprised that there are line endings causing problems like an erroneous `^M`. 

We have a very rough prototype windows installation guide written by another member of our community in issue #403, but beyond that my best recommendation is cloning it directly on a UNIX system, perhaps in an Ubuntu virtual machine. That should hopefully fix some of the line ending issues. 

Sorry for the inconvenience and I hope we can work something out! Let me know if you have any other questions.

**Comment by Nebrethar** [comment]
@dota17 Are you using an Ubuntu Subsystem for Windows along with a Windows installation? Or an Ubuntu VM with a shared filesystem? If  it isn't either you can disregard my message, but this is some experience of mine.

On both of these types of systems, I've had a similar issue and it was fixed by creating a virtual environment with the tool `virtualenv' instead of python's built-in with the flags provided.

`virtualenv -p python3 envname`

The other important part for fixing my similar issue was to clone the repo directly with `git` on ubuntu. I can put augur into my windows filesystem, but I **must** use the ubuntu side to gather and instantiate the files. (it's probably for permissions)

**Comment by dota17** [comment]
Thank you for your quick reply and advice!

Well, For some reason, I can't clone source package directly on Ubuntu at that time. So my original intent was to clone it on Windows, then compress it and upload it to Ubuntu. For now, I will no longer try to install it on Windows, I will use the Ubuntu 18.04 inside the DOCKER.

And now, the installation process run soomthly! 

The only problem is that it takes too much time and need to do a lot of interactive options.
