### ISSUE TITLE
Using a sqlite database that can be created by for a single project

### ISSUE THREAD

**Issue by dmgerman** [chaoss/augur#55]
Sean (and others),

I think the biggest challenge of using ghdata is that it relies on GHtorrent.

What about having the ability to use a database created from a given repository that mimics the schema
of GHtorrent. The idea is that, if one is interested in running ghdata on a given project, this person can create the corresponding database (with a script in ghdata or maybe another tool) and then being able to run ghdata on such database.

--dmg

**Comment by howderek** [comment]
Hello @dmgerman we appreciate your feedback and I apologize for the delayed response. I absolutely agree that GHTorrent is the largest hurdle for using GHData. We are exploring solutions and will include your SQLite suggestion in our discussions :)

**Comment by sgoggins** [comment]
@dmgerman : there is no coupling to the GHTorrent as a data source.  If you mimic the schema from another source, that will work. The challenge, technologically, is that the GHTorrent schema requires queries more complex than sqllite will support in order to operationalize the metrics. 

We could refactor some of that with pandas.  

Is the main aim here to have a developer version on lighterweight technology?

**Comment by dmgerman** [comment]
Can you give me an example of a query that SQLite will not be able to handle (that mySQL can)? In my experience it is the other way around (mySQL does not support merge joins, for example).

The goal is to change the need for GHTorrent to a script that does the equivalent mining, but only for one project. That will be significantly easier than having to install GHtorrent.

**Comment by howderek** [comment]
@dmgerman, [GHTorrent](https://github.com/gousiosg/github-mirror/) appears to already support SQLite and can be configured to only load data for a set list of repositories. If you would like to add SQLite support to ghdata, you could either modify [ghtorrent.py](https://github.com/OSSHealth/ghdata/blob/master/ghdata/ghtorrent.py) to work with both MySQL and SQLite, or add another data source focused on SQLite.

**Comment by sgoggins** [comment]
I think there are specific challenges being addressed in this issue:
1. Wanting to run GHData against a smaller dataset, or against a dataset that is not captured in GHTorrent (i.e., not a GitHub repository). We think this will be accomplished working the Perceval as a mapper/aggregator. This is something Jesus and I are discussing as part of the CHAOSS project
2. Actual support for SQLLite: SInce GHTorrent now provides .csv files by default, I think a subset could be mapped into SQLLite as @howderek notes above.

**Comment by howderek** [comment]
Hello @dmgerman,

I just wanted to follow up on your feedback about GHTorrent being burdensome. We have discussed a new architecture that will make it so that Augur does not rely on GHTorrent (which we agree is an issue), which we will work on implementing in the coming months.

Thank you again for your feedback!
