### ISSUE TITLE
Unable to retrieve data from endpoints[GSoC]

### ISSUE THREAD

**Issue by aksh555** [chaoss/augur#561]
Hello, I have started with the machine learning micro-tasks, and have installed Augur on my local system. Working in the dev branch.
![Screenshot from 2020-02-28 04-40-12](https://user-images.githubusercontent.com/25505971/75499861-4ce09b00-59f1-11ea-8475-6e489d22fd17.png)

Trying to run a jupyter notebook,(similar to the one in dev branch) where JSON data is collected from the endpoints, but I'm unable to do so. I've attached some screenshots too.
Can someone guide me on how to resolve this?
![Screenshot from 2020-02-28 06-04-36](https://user-images.githubusercontent.com/25505971/75499812-2d497280-59f1-11ea-92a3-ce850e20e50f.png)

**Comment by ccarterlandis** [comment]
Hi @aksh555! I'm sorry to hear you've been having issues. Can you share a link to the full notebook to which you're referring? I can't see the code causing the errors in the second screenshot you attached.

**Comment by aksh555** [comment]
> Hi @aksh555! I'm sorry to hear you've been having issues. Can you share a link to the full notebook to which you're referring? I can't see the code causing the errors in the second screenshot you attached.

Hi @ccarterlandis, Thanks for reaching out!
This is the link https://github.com/chaoss/augur/blob/dev/notebooks/Scikit%20Learn%20-%20Isolation%20Forest.ipynb which I was referring. I am using a similar notebook by changing the port accordingly and running `make dev`. I hit the endpoint, but the data frame isn't formed.
![Screenshot from 2020-02-29 08-03-40](https://user-images.githubusercontent.com/25505971/75599368-3d815080-5aca-11ea-96f5-bb8d9c6f4761.png)
and when I visit the URL,
![Screenshot from 2020-02-29 07-56-57](https://user-images.githubusercontent.com/25505971/75599370-41ad6e00-5aca-11ea-8052-e9a18835bcba.png)
For now, I'm able to load the data to a dataframe directly from the local postgres database though.

**Comment by ccarterlandis** [comment]
Ah, okay. If I remember correctly, @gabe-heim was the one who wrote that notebook as a test bed for our new implementation of our insight & anomaly detection worker. He would be to one to ask questions about the notebook, but if you're interested in the machine learning aspect of this notebook, I suggest completing some of the [ML microtasks](https://github.com/chaoss/augur/issues/545), as that notebook is approximately 2 months out of date and we've changed a lot since then. Hope this helps!

**Comment by aksh555** [comment]
> Ah, okay. If I remember correctly, @gabe-heim was the one who wrote that notebook as a test bed for our new implementation of our insight & anomaly detection worker. He would be to one to ask questions about the notebook, but if you're interested in the machine learning aspect of this notebook, I suggest completing some of the [ML microtasks](https://github.com/chaoss/augur/issues/545), as that notebook is approximately 2 months out of date and we've changed a lot since then. Hope this helps!

Yes, while doing the ML microtask I was seeing this notebook and tried collecting data on similar lines. For now I'm loading the data from the local Postgres database.
Thanks!

**Comment by ccarterlandis** [comment]
Sounds good!! I'll close this issue but if anything else comes up please don't hesitate to reach out!!

**Comment by gabe-heim** [comment]
@aksh555 Sorry for the trouble you ran into trying to get the notebook to work. I am going to fix it and push it because I think it is a great example for contributors looking to work on the ML microtasks. I will reopen the issue until it is working properly.

**Comment by gabe-heim** [comment]
<img width="1252" alt="Screen Shot 2020-03-02 at 6 02 40 PM" src="https://user-images.githubusercontent.com/20764846/75730317-77c63a00-5ce4-11ea-9c59-503992404873.png">
@aksh555 The issue you are running into is because the host/port you have in the endpoint url is incorrect. It should be the host/port that the backend api is running on, but you have the frontend host/port included in the url. 
`dev` branch is now updated to include a helper function in that notebook that will read the correct parts of your `augur.config.json` and puts them into the url for you. If you were wondering, the following part of your config determines the host/port the backend api will run on:

```
"Server": {
        "cache_expire": 3600,
        "host": "0.0.0.0",
        "port": "5002",
        "timeout": 60,
        "workers": 8
    },
```

Don't hesitate to reopen or ask questions if you are still having issues!

**Comment by aksh555** [comment]
> <img alt="Screen Shot 2020-03-02 at 6 02 40 PM" width="1252" src="https://user-images.githubusercontent.com/20764846/75730317-77c63a00-5ce4-11ea-9c59-503992404873.png">
> 
> @aksh555 The issue you are running into is because the host/port you have in the endpoint url is incorrect. It should be the host/port that the backend api is running on, but you have the frontend host/port included in the url. `dev` branch is now updated to include a helper function in that notebook that will read the correct parts of your `augur.config.json` and puts them into the url for you. If you were wondering, the following part of your config determines the host/port the backend api will run on:
> ```
> "Server": {
>         "cache_expire": 3600,
>         "host": "0.0.0.0",
>         "port": "5002",
>         "timeout": 60,
>         "workers": 8
>     },
> ```
> 
> Don't hesitate to reopen or ask questions if you are still having issues!

Thanks for resolving that @gabe-heim ! :smile: 
It works perfectly now, I didn't realize that it was backend server's host/port which was to be used
