### ISSUE TITLE
Queries about the Gitlab Worker data model[To be implemented]

### ISSUE THREAD

**Issue by mrsaicharan1** [chaoss/augur#580]
**Model Schema expectation for Gitlab Data Collection Worker**
This query is with regard to the schema which would be created during the implementation of the GitLab Data Collection Worker. After carrying out research pertaining to GitLab's internal API & how it interacts with their data model, there are some commonly used data tables such as `issues`, `pull_requests`, `commits` etc with respect to GitHub. The Question -- Should we be using the existent tables present in the augur schema to store the data during the collection process[Additionally creating tables which are not common] (or) create a new collection of tables solely for GitLab?

I'd prefer the creation of `gitlab_<data_model_name>` tables under the augur_data schema but thought it would be great to gain some inputs from the community.
Adding, I'd also love to hear about any suggestions as I'm attempting to chalk out a data model outline for the idea.

**Comment by ccarterlandis** [comment]
@sgoggins probably can phrase this better, but the primary goal of our schema design is to have a unified model of as many pieces of the open source ecosystem as we reasonably can. In this case, "unified" essentially means that our goal is transform similar data in a variety of sources and formats into a common structure. A more specific example: 

In the case of GitLab and GitHub, our goal would be implement in the GitLab worker in such a way that it can use the schema of the pre-existing tables where it would make the most sense to do so. While GitLab and GitHub present their data in different formats, our aim is to "translate" those different formats into a common structure, as otherwise we would have to duplicate queries across data sources (and thus across different table sets), which greatly increases the complexity of Augur on multiple levels. 

This unified structure also allows us to specify different data sources in a query (e.g. using GitHub's commit data vs. GitLab's commit data vs. Facade's commit data) and gives us the ability to synthesize data across data sources; for example, we could write a query comparing commit activity to mailing list activity, and we would not be tied to any one specific mailing list data source or commit data source, and in fact we could use 2 commit data sources at the same (eliminating duplicates) to try to fill in "holes" in the data, if we think any exist.

Where necessary, sometimes we do need to alter the structure of existing tables or add helper tables. Try to design your data model with changing what already exists if you can, but if you think there is **truly** no other way to model the data, we can discuss the possibility of making alterations. Hope this helps!

**Comment by mrsaicharan1** [comment]
@ccarterlandis yeah! the basic principle of augur is to compare metrics such as commits and other info across various data sources to see the differences and how well they compare to each other. So that would explain the unified data model and GitLab using Github's schema. Nice! 
Yeah, there are might be some variations to this but more or less, this seems to be the right way to do it! If there might be any changes to the schema, I'll add it to the mockup.
Thanks for the pointers 😃

**Comment by gabe-heim** [comment]
@mrsaicharan1 It is also important to note the `data_source` column for these tables, this is the main way to distinguish the platform the issue/pr/commit is on.

**Comment by mrsaicharan1** [comment]
@gabe-heim Yeah! Also, I noticed your comments on my previous PRs. I'm really interested in the main implementation of the workers and how we could integrate other data sources.
It would be great if you could point me to some tasks alluding to them. Thanks!

**Comment by shrutisatish00** [comment]
Hello this is Shruti, an outreachy applicant. I am only starting out learning ML and thought that this would be a good project to learn on the go. I was hoping for some guidance and would really appreciate it if someone could point me to new and relatively easy issues.

**Comment by mrsaicharan1** [comment]
Here's the first draft of my GSoC Proposal for the GitLab Data Collection Worker & Test Coverage Improvement! I'd really appreciate it if you could drop in a review :D @ccarterlandis @gabe-heim @sgoggins  Thanks
[Proposal Link](https://docs.google.com/document/d/1PUxvJt_uVbX3iqom1PtTMMfa5u5wB-MKuVMMiLsU7dw/edit?usp=sharing)

**Comment by ccarterlandis** [comment]
Hi @shrutisatish00, we are glad you want to contribute! Our ML microtasks are outlined in issue #558. If you have any other questions please feel free to open an issue!

**Comment by ccarterlandis** [comment]
@mrsaicharan1 just gave your proposal a glance and it's already looking great!! I will leave some detailed review comments in the near future but you're off to a great start!

**Comment by abhinavbajpai2012** [comment]
@ccarterlandis I had a question regarding the schema. As Gitlab (and it's API) keep on changing with the addition of features, There can be a scope to add more columns to the schema as more data would be made available with time. Are we interested in only a set of variables and keep the schema constant or should it be flexible to adjust any new data being made available through the API?
Example - Today I had only 23 variables available through the API while let's say tomorrow I get 24 due to the addition of some feature in Gitlab. In this case, a changing schema with the addition of column might be preferred.

**Comment by mrsaicharan1** [comment]
> @sgoggins probably can phrase this better, but the primary goal of our schema design is to have a unified model of as many pieces of the open source ecosystem as we reasonably can. In this case, "unified" essentially means that our goal is transform similar data in a variety of sources and formats into a common structure. A more specific example:
> 
> In the case of GitLab and GitHub, our goal would be implement in the GitLab worker in such a way that it can use the schema of the pre-existing tables where it would make the most sense to do so. While GitLab and GitHub present their data in different formats, our aim is to "translate" those different formats into a common structure, as otherwise we would have to duplicate queries across data sources (and thus across different table sets), which greatly increases the complexity of Augur on multiple levels.
> 
> This unified structure also allows us to specify different data sources in a query (e.g. using GitHub's commit data vs. GitLab's commit data vs. Facade's commit data) and gives us the ability to synthesize data across data sources; for example, we could write a query comparing commit activity to mailing list activity, and we would not be tied to any one specific mailing list data source or commit data source, and in fact we could use 2 commit data sources at the same (eliminating duplicates) to try to fill in "holes" in the data, if we think any exist.
> 
> Where necessary, sometimes we do need to alter the structure of existing tables or add helper tables. Try to design your data model with changing what already exists if you can, but if you think there is **truly** no other way to model the data, we can discuss the possibility of making alterations. Hope this helps!

@abhinavbajpai2012 I'm guessing that this should answer your question.
 Suppose we have a new attribute/"feature" added to Gitlab. At that point in time, GitLab would be the only data source possessing that feature. If we were to bring it in, we could obtain GitLab specific metrics but there wouldn't be another data source to compare it with.
I hope I'm right about that @ccarterlandis 😄

**Comment by abhinavbajpai2012** [comment]
Actually I once used Stitch which is a subscription-based/paid data collector worker for Lever and JIRA which pushes data to Big Query / AWS Redshift. It used to add extra columns for new attributes being added. This idea felt cool to me as storing extra data should not create a problem but could be used later.

**Comment by sgoggins** [comment]
@abhinavbajpai2012 : We definitely want the GitLab worker to map into the existing schema.

**Comment by ccarterlandis** [comment]
Since it seems the questions have been answered, I'm going to go ahead and close this issue, but feel free to reopen this issue or open another if I'm wrong 😄
