### ISSUE TITLE
Broken links on documentation page

### ISSUE THREAD

**Issue by dnabanita7** [chaoss/augur#597]
The links of the [augur docs](https://oss-augur.readthedocs.io/en/dev/getting-started/installation.html). The link to unified data model, Makefile commands, Data collection documentation are broken.

**Comment by ccarterlandis** [comment]
Hi @Naba7, thanks for letting us know about this. Looks like the data model link is broken due to an incorrect extension (`.rst` instead of `.html`) and the other two look to be incorrect path names. We're currently re-working our documentation up from the ground up to prep for our upcoming release, but I'll keep this issue open to serve as an impetus to get it done ASAP. 😄

**Comment by Adarsh-NP** [comment]
@ccarterlandis even the link to python documentation is broken, if you need someone to fix the links in documentation or anything related to the documentation that is doable, I can help.
Thanks.

**Comment by sgoggins** [comment]
@Adarsh-NP : We could definitely use help reading the documentation in the doc-a-thon branch and identifying issues in that branch that can be fixed. It has evolved significantly since you opened this issue.  Can you look at that branch and try an install and either fix/clarify what you think needs addressing or open specific issues?

**Comment by Adarsh-NP** [comment]
Hello sir,
Sure I will try to do that.
Thanks for asking.

**Comment by ccarterlandis** [comment]
Documentation has been reworked as of v0.12.0, so these links have been fixed.
