### ISSUE TITLE
Cannot find module '../../../../../augur.config.json'

### ISSUE THREAD

**Issue by NodiraIbrogimova** [chaoss/augur#611]
Dear Augur Project team,
I wanted to contribute to this project as an **outreachy** intern. I started with these [microtasks](https://github.com/chaoss/augur/issues/559) and followed the [documentation](https://oss-augur.readthedocs.io/en/dev/getting-started/installation.html) for installation and running the project in my development environment.
Details about my development environment:

- MacOS Mojave
- Version 10.14.6 

1. I did `make clean` in augur (folder path) and prompted `make install`. 
2. `cd` to frontend  and installed `npm`
3. Prompted `npm run start`, but I'm getting an error in the screenshot below. 

I'm really beginner in Machine Learning and I'm really eager to learn it. I would really appreciate the guidelines to start my contribution to [**Machine Learning for Anomaly Detection in Open Source Communities**](https://www.outreachy.org/outreachy-may-2020-internship-round/communities/chaoss/#machine-learning-for-anomaly-detection-in-open-sou) project.

<img width="1338" alt="Screen Shot 2020-03-16 at 6 07 31 PM" src="https://user-images.githubusercontent.com/11291840/76762720-9ed83d80-67b3-11ea-8f9c-db4a48421374.png">

**Comment by NodiraIbrogimova** [comment]
@germonprez @sgoggins  @gabe-heim

**Comment by ccarterlandis** [comment]
Hi @NodiraIbrogimova, can you verify that there is a non-empty file called `augur.config.json` in your root `augur` directory? In your case, it looks like it should be in `/Users/nns/Documents/outreachy/augur/`. This is the configuration file used across the project, and the frontend needs to read some values from the config to know where the backend API is located. If this file does not exist, you'll see an error like the one you have above. Let me know how it goes!

**Comment by NodiraIbrogimova** [comment]
Hi @ccarterlandis, thank you for a detailed answer. I couldn't find the file in `augur` directory. Where can I find the file? 
P.s. I'm working on `dev` branch as provided in guidelines.

**Comment by ccarterlandis** [comment]
You'll need to create one, since it doesn't exist. `make install` [1]  _should_ have created one for you, but if it doesn't I suggest running `./scripts/install/config.sh` manually from the root `augur/` directory (this is the helper script that `make install-dev` runs).

 If that doesn't work you could also try running `augur configure generate` (still in the root directory) and one will be generated for you. You'll need to replace the default credentials with your own after you create it, or you can optionally pass them to the command when you run it; pass the `--help` flag to see all the available parameters (if you don't specify a parameter value, the default will be used).

[1]: I recommend using `make install-dev` to install dependencies specifically for development, but that is not mentioned in the docs (it's a very new command) so don't worry about not knowing that. I am actually working on the new docs right now, hopefully they will be available sooner rather than later 😄

**Comment by NodiraIbrogimova** [comment]
@ccarterlandis `augur configure generate` in `augur` - project root directory worked like a charm :) Thank you. 

How can I ask questions in case of completing microtasks and/or searching for more details with new ideas contribution? Please let me know.

**Comment by ccarterlandis** [comment]
Glad to hear it worked!! I'll go ahead and close the issue.
You can find info for our microtasks here:

Machine Learning: #558 
Single-Sign-On (SSO): #557 
GitLab Worker Implementation: #559 

Hopefully these give you some ideas to get started!! Please feel free to open more issues if you run into any other problems or want to brainstorm new tasks!!

**Comment by NodiraIbrogimova** [comment]
@ccarterlandis for brainstorming new tasks is it ok if I open more issues?
