### ISSUE TITLE
pull request commits model block missing from housekeeper on installation

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#681]
**Describe the bug:**
We now have the pull request worker pulling the pull request commits. That block is not being added to the housekeeper on the `make install-dev`

It looks like this: 

```
	    {
                "delay": 86400,
                "given": [
                    "github_url"
                ],
                "model": "pull_request_commits",
                "repo_group_id": 0
	    }
```

**Other Info":**
`dev branch`

**Comment by ccarterlandis** [comment]
It's not in there because this is the first time I've heard of this 😁 I will add it to the default config, but for future reference if you need to add something to the default config and don't want to wait for me to do it, just add it to contents the `default_config` variable defined at the top of `augur/cli/configure.py` and it will be part of the default installation from then on.

**Comment by ccarterlandis** [comment]
Is that the `delay` value you want? All the other jobs have a delay of either `150000` or `1000000` and I think we should remain consistent in one or other unless there's a good reason not to.

**Comment by sgoggins** [comment]
Stay consistent on delay values. 
Yeah, ahem, sometimes folks add new features but forget to tell us about the `augur.config.json` parameters. But they are good people. :D

**Comment by ccarterlandis** [comment]
No problem, I totally get it! Which `delay` value should I use?

**Comment by ccarterlandis** [comment]
I ended up going with `15000`.
