### ISSUE TITLE
Software pages

### ISSUE THREAD

**Issue by tharun143** [chaoss/augur#724]
@ccarterlandis Can u explain to me about the work that I have to do for writing the software page for Augur in the CHAOSS website. As @klumb already mentioned us in issue #[184 ](https://github.com/chaoss/website/issues/184)in the CHAOSS repo. Can u explain to me more about what I have to do?

**Comment by ccarterlandis** [comment]
Hi @tharun143, unfortunately I don't know anything else outside the scope of what's mentioned in that issue. From my understanding of said issue, and from when Kevin asked me help out, I can provide any information you need about Augur so that you can put it on the website, including any technical details, roadmaps, contributor information, really whatever you need.
I am more than happy to provide any of that information, but I would first like to know a few things:
1. How much space (characters/words/lines/pages/etc) of content are you looking for? Are there minimum/maximum requirements?
2. Where will this content live? On its own dedicated page? On the "Participate" page? Somewhere else? All/none of the above?
3. Who will this be targeted at? Potential technical contributors? Potential non-technical contributors? New CHAOSS members? Existing CHAOSS members?

This is not an exhaustive list, just some things that would really help me to focus whatever information I write up for you. If you don't know the answers to any of these that is also okay, we can decide together 😄 if you have examples of what you are looking for, that would also be very helpful. If my interpretation of what we need to is different than yours, by all means please let me know. Looking forward to working with you!

**Comment by sgoggins** [comment]
This has been addressed.
