### ISSUE TITLE
Augur cannot find my virtual environment

### ISSUE THREAD

**Issue by Nebrethar** [chaoss/augur#909]
**Description:**

I tried some debugging and it told me I am not in a virtual environment when I certainly am.

**How to reproduce:**
1. `make install-dev` with a new augur clone

**Expected behavior:**
I expected to be able to use the installer once I was in a venv

**Screenshots**
![image](https://user-images.githubusercontent.com/34951354/92539267-9282e980-f206-11ea-8609-e9d4033b2a1e.png)

**Log files**
This is all the information that I get.
```
*** We noticed you're not currently inside a virtual environment. Augur MUST be run inside a virtual environment. ***
*** Would you like us to generate a environment for you automatically? If you select no, you must create it yourself. [Y/n] n

Please create & activate your virtual environment and rerun the installation command when you're finished.
make: *** [Makefile:55: rebuild] Error 1
```

**Software versions:**
 - Augur: latest master
 - OS: Ubuntu 20.04

**Comment by Nebrethar** [comment]
Also note, there is a typo in the error message

Would you like us to generate a environment for you automatically? If you select no, you must create it yourself.
Would you like us to generate **an** environment for you automatically? If you select no, you must create it yourself.

**Comment by ccarterlandis** [comment]
Augur checks for the presence of an environment variable called `ENV` to be populated with the name of your environment to determine if you're in a virtual env. Do you see an envvar called `ENV` in your environment? How did you create the virtual env?

**Comment by Nebrethar** [comment]
I used the command I usually use to create a venv. This has worked with augur in the past.

`python3 -m venv /virtualenvs/augur`

This is the result when I activate my venv, and then try to install augur

![image](https://user-images.githubusercontent.com/34951354/92615909-3b6f2a00-f283-11ea-9909-7c4f69ef49b8.png)

**Comment by ccarterlandis** [comment]
Okay, I see what's going on. The problem isn't Augur, the problem is that you're using `sudo`. Your environment changes to mock the superuser when you use `sudo`, and you activated the venv for YOUR user, not the superuser. `sudo` is also not supported for Augur installation, nothing Augur needs will need root access. If your version of Augur does not work without `sudo` then something else is wrong, please try to run `make install-dev` again without `sudo` and see if that fixed your issue.

**Comment by Nebrethar** [comment]
Ah, I see. That worked!! Sorry about that - I tend to use sudo frivolously and it gets me in jams like this. 😄 

I'd like to keep this open until the sudo distinction is added to the documentation.

**Comment by Nebrethar** [comment]
Here's the picture of the make install-dev running and the virtual environment being found

(and #908 again)

![image](https://user-images.githubusercontent.com/34951354/92625686-96f2e500-f28e-11ea-9ac5-05b77dee56a6.png)

**Comment by sgoggins** [comment]
@Nebrethar : You need `sudo` for `augur-spdx` because it installs system level scanners. But that's a separate repo, and a byproduct of a dependency we inherit from Fossology. Straight up Augur, as @ccarterlandis notes, never requires `sudo` ... HOWEVER .... if you have run `run install` or `run install-dev` with `sudo` on your machine even *once*, you have to go change the ownership on all of your NodeJS files ... because nobody but `sudo` can make them *yours* again. So, like a `sudo chown -R {NodeJS location}`

**Comment by sgoggins** [comment]
NodeJS, or "Full Stack NodeJS" does have a use case for system level installations of NodeJS, but Augur does not. And, frankly, I am only imagining the system level use case, but I still think nobody should ever "do that". Except maybe on a production server with a bunch of NodeJS apps where you want to control the versions so that everything is consistent ... but Augur doesn't need to own a whole server like that.

**Comment by sgoggins** [comment]
Don't use `sudo` and we fixed a bunch in the latest release.
