### ISSUE TITLE
Cannot install augur to test without setting up DB

### ISSUE THREAD

**Issue by Nebrethar** [chaoss/augur#910]
**Description:**
I cannot install augur for development without setting up a working database with an Augur schema. I see some problems with this:

- If I were a new user who wanted to "test out" the software, I would be gone once I realized that requirement. That's a lot of overhead to give to curious users.
- I'm going to be working with some software that could be potentially (accidentally) harmful to a major Augur database. I just needed to make some edits to the frontend and I don't want to do that.

**How to reproduce:**
1. Start installation
2. Quickly prompted to set up a DB

**Expected behavior:**
I am looking for some kind of way to install augur to tweak it, without setting up a DB.

**Software versions:**
 - Augur: latest master
 - OS: Ubuntu 20.04

**Comment by ccarterlandis** [comment]
I don't really think this is an issue. To your first point, we would expect new users to use Docker to set up their database (much, much, much easier - it's 1 shell command) before expecting them to go to the trouble of setting up a permanent one. To your second point, the database is required by all parts of the application. Without the database, there is no data for the frontend to display, so unless you're tweaking non-data UI elements, you need a database. The API and workers are completely non-functioning without a DB either; given that those 3 pieces make up pretty much all the application, it doesn't make sense for us to support using Augur without a DB since there would be basically no functionality.

That being said, if you really do just want to tweak the frontend, you can `cd frontend` and then `npm run serve`. No data will load and most things will be broken until you set up a DB and connect the API, but it should work in theory.

**Comment by Nebrethar** [comment]
It just seems to me like many of these function commands are obtained by word-of-mouth. I just wanted to tweak a frontend without data  - but the method to do that is either hard to find in the documentation or not present at all.

**Comment by ccarterlandis** [comment]
Which function commands? The ones to run the frontend? Those are not documented anywhere - I am the only person who really contributes to the documentation and the installation process, and there has always been higher priority things that need to be fixed or documented first. I am also not familiar with our frontend at all, so I have no idea how to write the docs beyond the most basic commands and such. Sorry about that, I know it's frustrating...

**Comment by sgoggins** [comment]
This is fixed in the latest release of Augur.
