### ISSUE TITLE
Improved handling of redirects for orgs and repos

### ISSUE THREAD

**Issue by geekygirldawn** [chaoss/augur#915]
While the GitHub API automatically follows redirects and continues gathering data from the newly redirected location, this creates unexpected behavior for users. For example, someone looking in pivotal.osshealth.io for the repo group vmwarepivotallabs would think that the data is missing. However, they could find the data by looking for the pivotalservices repo group, which was the original name of the GitHub org. In this case, all of the repositories at https://github.com/pivotalservices have been redirected to https://github.com/vmwarepivotallabs

Where this gets tricky is that GitHub redirection seems to happen at the repository level, not at the org level. Because of the reirection, https://github.com/pivotalservices looks like an empty org, but you can see that if you go to one of the original repositories, like https://github.com/pivotalservices/binder, you'll be redirected to the corresponding repo in vmwarepivotallabs, in this case: https://github.com/vmwarepivotallabs/binder

In addition to displaying the new information correctly in the front end, the corresponding database fields will also need to be updated. For example: repo_groups.rg_name, repo_groups.description, repo_groups.website, repo.repo_path, repo.repo_name, repo.url, and probably others that I'm not noticing.

There are also a few different cases for redirection that should be considered. The above example talks about moving an entire org and all of the repos within it, which is probably the most complex case, but there are other simpler cases:

- A single repo moved to a new org. Example: http://github.com/Spring-projects/spring-batch-admin-samples to https://github.com/spring-attic/spring-batch-admin-samples
- A single repo renamed within the same org. Example: http://github.com/Pivotal-Field-Engineering/word_cloud-spring-kafka-k8s-workshop to https://github.com/Pivotal-Field-Engineering/word_cloud-spring-kafka-on-k8s

**Comment by geekygirldawn** [comment]
@sgoggins this is the other feature request we talked about. 

@ivanayov again, this is another one that you might be interested in working on?

**Comment by hqrshguptq** [comment]
Can I take this over?

**Comment by hqrshguptq** [comment]
Hi @geekygirldawn , Can I take this over?

**Comment by sgoggins** [comment]
@hqrshguptq : We would welcome the assistance! The development guide for Augur is being worked on as we speak, and there's a pull request open right now that @Nebrethar is reviewing (From @ccarterlandis ) that makes our docs a bit easier to follow. 

As long as the repository is only changing organizations, I think the process should: 
1. Queue the change in two tables in the `augur_operations` schema. 
2. These two tables should have the same structure as the `repo` and `repo_group` table in the `augur_data` schema PLUS one more value: `new_repo_git` in the `repo_change_queue` table (possible names for new tables) and `new_repo_group` in the `repo_group_change_queue`. 

The queue tables are necessary because, many workers are typically gathering data constantly, and unless we queue changes, we are likely to trip up workers if we handle this in real time. Augur doesn't maintain a central awareness of which worker is pulling data for which repo at any point in time, so in this way the WHEN we collect data is a non-deterministic function of new data size, and data collection order, and data collection frequency. 

This video is not Hollywood level, but it does give a nice overview of how the workers "work" : https://www.youtube.com/watch?v=0s--LS736Vg&feature=youtu.be

@gabe-heim , @ccarterlandis , @Nebrethar , and I are keen to support your activity here. And if you suggest another path to solution, we are completely open to it ... My aim here was only to surface factors to consider.  @geekygirldawn is the primary person to make happy here. :) THANK YOU!

**Comment by sgoggins** [comment]
@hqrshguptq : You should make a fork of augur, but work off the `dev` branch. The docs are bit more up to date there as well: 
https://oss-augur.readthedocs.io/en/dev/

**Comment by geekygirldawn** [comment]
Hi @hqrshguptq - I wanted to just check in to see if this was something you are still working on and see if you needed any additional info :)

**Comment by geekygirldawn** [comment]
Hi @hqrshguptq - I wanted to just check in to see if this was something you are still working on and see if you needed any additional info :)

**Comment by geekygirldawn** [comment]
Assigning to @ivanayov since it looks like there hasn't been any progress, and she's offered to pick it up.

**Comment by geekygirldawn** [comment]
Hmmm, for some reason, I can't actually assign @ivanayov to this issue 🤷‍♀️

**Comment by ccarterlandis** [comment]
Weird, I can't either. Maybe she needs to be added to the CHAOSS organization, or given at least `Triage` access to Augur repo as an outside collaborator?

**Comment by ivanayov** [comment]
@ccarterlandis AFAIR I saw the invitation after it had expired, so couldn't join the org

**Comment by ccarterlandis** [comment]
@ivanayov just sent you another!

**Comment by geekygirldawn** [comment]
@ivanayov @sgoggins I was hoping to get a status update on this feature. This is something that's becoming pretty important for us because we've moved a bunch of pretty important projects from one org to another :)

**Comment by sgoggins** [comment]
@ivanayov : I know you are close to completing this  ... There were some errors in the pull request. Do you have time to take a looK?

**Comment by sgoggins** [comment]
@ivanayov : This is my weekly, weak, plea for help. :)

**Comment by ivanayov** [comment]
@sgoggins I'll take a look.

**Comment by sgoggins** [comment]
We are testing a recent pull request from @ivanayov right now.
