### ISSUE TITLE
Needed help in the technical requirement specifically for Augur within the community-handbook 

### ISSUE THREAD

**Issue by jaskiratsingh2000** [chaoss/augur#937]
Hey!

I am one of the **[Google Season of Docs](https://developers.google.com/season-of-docs)** aspirants working on the "**[Community-Handbook](https://github.com/chaoss/community-handbook)**" under the CHAOSS project. 
This issue is specific around the "Development" page under the community-handbook.

As you could see in this **[link](https://chaoss-project.gitbook.io/community-handbook/development#technical-requirements)** I have laid down the technical requirements for the "all projects" under the CHAOSS. And from my understanding, the projects are more focused on Python language but I am not sure that if Augur has any other language or framework written in. Though I see within some repositories that there are some other languages too listed in the sidebar but not sure. So I wanted to ask specifically if there are any other technical requirements for this project specifically, can someone write it down under the same section with the references to pre-surf around before chiming directly into the development stuff?

Also, here is another page that reflects the **[contribution workflow](https://chaoss-project.gitbook.io/community-handbook/development/contributing-worfkflow)** followed for any technical project. So feel free to suggest changes for it as I am not technically strong enough so I would need someone help in that if there is a requirement of any addition of more technical stuff.
Below are the respective links:

- Development page link: https://chaoss-project.gitbook.io/community-handbook/development
- Contribution Workflow: https://chaoss-project.gitbook.io/community-handbook/development/contributing-worfkflow

Your help would really be appreciable. 
Thanks!

cc @sgoggins @GeorgLink

**Comment by ccarterlandis** [comment]
@jaskiratsingh2000 I would be happy to help, I am very familiar with Augur's developer requirements & workflow. I'm a little unclear on what I need to do right now - is it just collecting helpful links for some of the other frameworks/languages Augur uses (like Flask and Vue.js), and then adding those links to that page?

I'll can take look at the contribution page as well, no problem. What is the best way to suggest changes for this, if I have any? Thanks!

**Comment by jaskiratsingh2000** [comment]
Hi @ccarterlandis Thank you very much for chiming in. I really appreciate your support in this regard,
So you are required to write any technical requirements we have for the Augur project on this page https://github.com/chaoss/community-handbook/tree/master/development
Just add the languages or the tools we are using along with the references for the people to grab the knowledge if they are not familiar with that.

You can create a PR on this page https://github.com/chaoss/community-handbook/tree/master/development

Thanks

**Comment by GeorgLink** [comment]
This is not a `requirement` but a **request** to help with the handbook content.

**Comment by sgoggins** [comment]
Can you convert documenation from .RST format to the GitBook format?

**Comment by ccarterlandis** [comment]
@sgoggins that wouldn't be useful in this case, this documentation does not already exist so it would be need to be written from scratch.

**Comment by sgoggins** [comment]
@ccarterlandis : I am trying to avoid having us create documentation in multiple formats.

**Comment by GeorgLink** [comment]
If you want to create that documentation for Augur, we can link to it from the CHAOSS Handbook. No need to duplicate information or have Augur documentation in multiple locations and format.s

**Comment by jaskiratsingh2000** [comment]
Yeap, Agreed!

**Comment by ccarterlandis** [comment]
> If you want to create that documentation for Augur, we can link to it from the CHAOSS Handbook

@GeorgLink that makes things much easier, I will do that instead! @sgoggins

**Comment by sgoggins** [comment]
Installation poses a roadblock for developers who have, for one reason or another, had one of these three issues. After years of troubleshooting, nearly every installation faces these issues: 

There are 3 main issues developers encounter when first installing Augur: 
1. The absence of a `gcc` or `fortran` copiler, required by numpy and nltk python libraries. 
2. Conflicting versions of Python: The fix is platform specific. On Max OSX, more often than not multiple versions of python have been installed by the OS, brew, Anaconda, or a combination of both. The result is some python commands are drawn from different paths because of how they are linked in `/usr/local/bin`
3. Multiple, or conflicting versions of postgresql. Sometimes, the absence of a functional `psql` function at the command line results. 

Lets add that to the handbook, @ccarterlandis ... (I'll do it) ... But @GeorgLink : I don't think software belongs in the community handbook. We have a robust readthedocs site here: https://oss-augur.readthedocs.io/en/dev/

It seems counter to common open source practice to include details like this in a community handbook. That's simply not how contributors and maintainers do their work. 

Perhaps there are other things for the handbook that are more stable, and slower to evolve? We don't have the funds to hire a typesetter.
