### ISSUE TITLE
Pull Request Worker Error

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#994]
I have not gotten a new pull request since 10/29. The files and commits are updating.
Is this related to the base_worker file changes @gabe-heim ? 

```
[32716] workers.pull_request_worker.44951 [INFO] GraphQL query failed: 
                {{ 
                  repository(owner:"pivotalservices", name:"pcfbackup-release"){{
                    pullRequest (number: 1) {{
                
                      files (last: 100{files}) {{
                        pageInfo {{
                          hasPreviousPage
                          hasNextPage
                          endCursor
                          startCursor
                        }}
                        edges {{
                          node {{
                            additions
                            deletions
                            path
                          }}
                        }}
                      }}
                    }}
                  }}
                }}
```

**Comment by sgoggins** [comment]
@gabe-heim : This seems to be a rate limiting anomalie. I have it collecting again.

**Comment by sgoggins** [comment]
I think what's happening is this instance has been getting updated a lot, and there are not actually any new pull requests until we get to the higher numbers. Nonetheless, this graphql query needs to be dealt with ASAP. Thanks, @gabe-heim

**Comment by ccarterlandis** [comment]
This repository does not exist anymore: https://github.com/pivotalservices/pcfbackup-release. That's why there are no more PRs to gather. Is this an actual issue then? I don't know what "dealt with" means in this context, as there is nothing wrong with the query structure itself; only the arguments. Can you please be more specific about what you mean if there is something I've missed?
