### ISSUE TITLE
GitHub Worker Error Handling

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#995]
There is a key mismatch in the github issues worker. This may be related to changes in @workerbase @gabe-heim . 

```
[8793] workers.github_worker.48912 [ERROR] Traceback (most recent call last):
  File "/home/sean/github/augur-pivotal/workers/worker_base.py", line 330, in collect
    model_method(message, repo_id)
  File "/home/sean/github/augur-pivotal/workers/github_worker/github_worker.py", line 308, in issues_model
    new_events = self.check_duplicates(j, event_table_values, pseudo_key_gh)
TypeError: check_duplicates() missing 1 required positional argument: 'key'

[8793] workers.github_worker.48912 [INFO] This task inserted 90 tuples before failure.

```

**Comment by ccarterlandis** [comment]
This is not due to a key mismatch. As the error states, the problem is that the call to `check_duplicates()` on line 308 of `github_worker.py` is missing an argument *called* `key`. This is happening because the method is declared like so:
```
@staticmethod
def check_duplicates(self, new_data, table_values, key):
...
```
As you can see, it's being declared as a static method, but still has the `self` parameter of an instance method, which does not make sense: static methods should not (and do not) have access to any instance variables. Thus, the function is treating `self` as the first regular argument, and thinks that there should be 4 parameters instead of just 3.

It seems this was introduced over the summer by Sai: 
![image](https://user-images.githubusercontent.com/31522931/97905393-80559100-1d07-11eb-91bc-9a472285f3b8.png)
This is the first I've heard of this issue, I'm really not sure how it managed to go this long undetected? Maybe I'm missing something here?

I think the solution here is to simply get rid of the `@staticmethod` generator; the method is in fact not even static to begin with, as it uses the worker's `self.logger`, which would not be available if it were truly static.
